hotList:
  url: https://api.tophubdata.com/nodes/
  # 在 https://www.tophubdata.com/dashboard 申请key
  key: 
  # type定义参考 https://www.tophubdata.com/all-nodes
  types: 
    - name: GitHub今日趋势
      code: rYqoXQ8vOD
      num: 5
      needSummary: true
    - name: CSDN今日头条热点
      code: n3moBVoN5O
      num: 5
      needSummary: true
    - name: 掘金全站最新
      code: proPW8meq6
      num: 5
      needSummary: true
    - name: 开源中国最新资讯
      code: 1Vd5x9av85
      num: 5
      needSummary: true
    - name: InfoQToday
      code: JndkZkAv3V
      num: 5
      needSummary: true
    - name: 机器之心最热文章
      code: DOvnNz1vEB
      num: 5
      needSummary: true

ai:
  url: https://api.moonshot.cn/v1
  # 在 https://platform.moonshot.cn/console/api-keys 申请key
  key: 
  role: 你是Kimi，你擅长对软件开发技术博客进行内容总结。你会为用户提供安全，有帮助，准确的回答。